### ISSUE TITLE
Curation of image list

### ISSUE THREAD

**Issue by shanilsasikumar** [shah/uniform-resource#12]
Hi @shah 
We can have a list of images from the curable content, So that featured image can be selected from the list.
   
Sample code returning image URLs using Cheerio selector
   ```
 var resObj = {}, // return object
//set a reference to the document that came back
$ = cheerio.load(responseHtml),
$images = $('img');
if ($images && $images.length) {
    resObj.images = [];
    for (var i = 0; i < $images.length; i++) {
        resObj.images.push($($images[i]).attr('src'));
    }
}
```

**Comment by shah** [comment]
@shanilsasikumar the initial code is now in the package, please add test cases and verify functionality.
