### ISSUE TITLE
Need to have option to fetch  Fav Icon 

### ISSUE THREAD

**Issue by geovlazar** [shah/uniform-resource#4]
Can this uniform resource will allow fetching the Fav iCon of the source site which we trying to get data?. In some cases along with the data from the source site we need to display the URL with favicon of the source website 
![image](https://user-images.githubusercontent.com/754612/90031194-93ddf680-dcda-11ea-8ce0-2fcfd345cda1.png)

**Comment by shah** [comment]
Yes @geovlazar this should be possible. Do you already have the code and just need to integrate it into `uniform-resource` or do we need to build the code?

See:
* https://github.com/Smile4ever/getFavicon-node
* https://www.npmjs.com/package/get-website-favicon

If a module is already doing what you need, it shouldn't take long to integrate.

**Comment by geovlazar** [comment]
Thanks @shah for your detailed response. 
If there are another module and component which do the same process we can follow that. But my point is if this feature also is a part of the `uniform-resource`  it will be great to for fetching Metadata of the Page, FavIcon, Image URLs. So that we can use the same in multiple places in the future.

**Comment by shah** [comment]
Yes, @geovlazar this can and will be fully integrated into `uniform-resource` but my question to you is how you suggest it should be incorporate and what you need. If you need just the URLs that's easy, if you need the actual binaries downloaded as attachments that's a bit more work. Please elaborate exactly what you need.

**Comment by geovlazar** [comment]
Thanks @shah for your response. As of the first version, we can continue like what is available now. My opinion is to include the download of actual binaries in the advanced versions and please consider this as an item in your Roadmap of enhancements
