### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by vprdnew** [shah/uniform-resource#5]
I ran on NodeJS v14.8.0 and TypeScript Version 3.9.7:

    npm install

I see the following errors, please investigate this.
```
code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vishnu/.npm/_logs/2020-08-13T08_04_24_023Z-debug.log
```
I tried to authenticate using

`npm login --`

I am able  logedin with my account. Again tried npm install but issue still exist.

`Logged in as vprdnew on https://registry.npmjs.org/.`

**Comment by shah** [comment]
This was because `npm login --registry=https://npm.pkg.github.com` was not used properly - that must be done one time with your GitHub ID and GitHub Personal Access Token (PAT).
